version: '3'
services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy
        container_name: nginx-proxy
        ports:
          - "80:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf:ro
        networks:
          - devbox
    moodle:
        image: moodlehq/moodle-php-apache:$MOODLE_DOCKER_PHP_VERSION
        volumes:
          - moodledata:/var/www/moodledata
          - $MOODLE_DOCKER_WWWROOT:/var/www/html
        depends_on:
          - postgres
        environment:
          - VIRTUAL_HOST=moodle.local
        networks:
          - devbox
    postgres:
        image: postgres:12
        environment:
          - POSTGRES_PASSWORD=postgres
        volumes:
          - pgdata12:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        networks:
          - devbox
    mailhog:
        image: mailhog/mailhog
        ports:
          - 8025:8025
        networks:
          - devbox
volumes:
    moodledata:
        external: true
    pgdata12:
        external: true
networks:
  devbox:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.31.0.0/16
